### ISSUE TITLE
Fonts missing in installation instructions

### ISSUE THREAD

**Issue by pfisterer** [pageauc/motion-track#2]
Thanks for all the work on this project. I just wanted to give it a try but first had to 

```
apt-get install fonts-freefont-ttf
```

before the calibration images were saved. Otherwise, the program crashed.

**Comment by pageauc** [comment]
Thanks pf

I will add to the install instructions although I have never run across this problem on either Jessie or Wheezie.  Have not tried with Jessie Lite.  It may be that this gets installed with Pillow or PIL and I install imaging with pi-timolo.  Also I install opencv from source so might be installed at that time.  Let me know what OS version you are running on your RPI.  I do not do very much error trapping in the code but have started doing it where ever it makes sense.  The motion-track code is just a demo I did as a fun exercise. and later wrote a prototype hotspot game and of course speed-track that has more application.  I also find issues with python2 and python3 syntax differences especially with opencv.

Regards Claude ...

**Comment by pfisterer** [comment]
Thank you! 

I've used Raspbian Jessie Lite (https://www.raspberrypi.org/downloads/raspbian/), cloned your repository, and executed your speed-track script. After installing the fonts everything seems to work fine.

**Comment by pageauc** [comment]
OK.  Thanks for the information.  I have had a few previous issues with Jessie Lite not having some expected libraries.  I guess that is why they call it lite.  I have used Jessie Lite on a few machines that run headless.  The regular Raspbian does have a lot of stuff that I don't use but when you need a desktop for testing opencv or a GUI application then it is essential.  Thanks for your help.

**Comment by pageauc** [comment]
FYI I have a newer Faster version using threading at
https://github.com/pageauc/motion-track/tree/master/speed-track-2

Let me know what you think.  Note this is still just a demo

On Wed, Apr 13, 2016 at 6:46 AM, Dennis Pfisterer notifications@github.com
wrote:

> Thank you!
> 
> I've used Raspbian Jessie Lite (
> https://www.raspberrypi.org/downloads/raspbian/), cloned your repository,
> and executed your speed-track script. After installing the fonts everything
> seems to work fine.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/pageauc/motion-track/issues/2#issuecomment-209363387

## 

See my YouTube Channel at http://www.youtube.com/user/pageaucp

**Comment by pageauc** [comment]
Instructions contain details for installing missing fonts in Jessie lite per
sudo apt-get install fonts-freefont-ttf
